import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const futura = localFont({
  src: [
    {
      path: "./fonts/Futura/FuturaCyrillicLight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Futura/FuturaCyrillicBook.woff2",
      weight: "350",
      style: "normal",
    },
    {
      path: "./fonts/Futura/FuturaCyrillicBook.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Futura/FuturaCyrillicMedium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Futura/FuturaCyrillic-Demi.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Futura/FuturaCyrillic-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Futura/FuturaCyrillicHeavy.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-futura",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/zao2pgo.css" />
        <link href="https://fonts.cdnfonts.com/css/futura-pt" rel="stylesheet" />
      </head>
      <body className={`${futura.variable} antialiased`} style={{ fontFamily: "Futura" }}>
        {children}
      </body>
    </html>
  )
}
